FullCon2/Controllers/KnowBaseAnexosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DBConnection;
using Domain;
using System.Text;
using System.IO;
using Microsoft.AspNetCore.Hosting.Server;

namespace FullCon2.Controllers
{
    public class KnowBaseAnexosController : BaseController
    {
        private readonly CoreDbContext _context;

        public KnowBaseAnexosController(CoreDbContext context)
        {
            _context = context;
        }

        // GET: KnowBaseAnexos
        public async Task<IActionResult> Index()
        {
            return View(await _context.knowBase.ToListAsync());
        }

        // GET: KnowBaseAnexos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var knowBaseAnexos = await _context.knowBase
                .FirstOrDefaultAsync(m => m.Id == id);
            if (knowBaseAnexos == null)
            {
                return NotFound();
            }

            return View(knowBaseAnexos);
        }

        // GET: KnowBaseAnexos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: KnowBaseAnexos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdKnowbase,arquivo,tipo,nome,Id,DataInclusion,UserName")] KnowBaseAnexos knowBaseAnexos)
        {
            if (ModelState.IsValid)
            {
                _context.Add(knowBaseAnexos);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(knowBaseAnexos);
        }

        // GET: KnowBaseAnexos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var knowBaseAnexos = await _context.knowBase.FindAsync(id);
            if (knowBaseAnexos == null)
            {
                return NotFound();
            }
            return View(knowBaseAnexos);
        }

        // POST: KnowBaseAnexos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdKnowbase,arquivo,tipo,nome,Id,DataInclusion,UserName")] KnowBaseAnexos knowBaseAnexos)
        {
            if (id != knowBaseAnexos.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(knowBaseAnexos);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!KnowBaseAnexosExists(knowBaseAnexos.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(knowBaseAnexos);
        }

        // GET: KnowBaseAnexos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var knowBaseAnexos = await _context.knowBaseAnexo.FirstOrDefaultAsync(m => m.Id == id);

            if (knowBaseAnexos == null)
            {
                return NotFound();
            }

            return RedirectToAction("Create", "Clientes", new { id = knowBaseAnexos.IdKnowbase});

            //return View(knowBaseAnexos);
        }

        // POST: KnowBaseAnexos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var knowBase = await _context.knowBaseAnexo.FindAsync(id);
            _context.knowBaseAnexo.Remove(knowBase);
            await _context.SaveChangesAsync();
            return RedirectToAction("Create","KnowBases", new { id = knowBase.IdKnowbase } );
        }

        private bool KnowBaseAnexosExists(int id)
        {
            return _context.knowBase.Any(e => e.Id == id);
        }

        public async Task<IActionResult> DownloadAsync(int id)
        {
            var knowBaseAnexos = await _context.knowBaseAnexo.FindAsync(id);
            var content = new System.IO.MemoryStream(knowBaseAnexos.arquivo);
            var contentType = knowBaseAnexos.tipo;
            var fileName = knowBaseAnexos.nome;
            return File(content, contentType, fileName);
        }

    }
}

FullCon2/Controllers/KnowBasesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DBConnection;
using Domain;
using Microsoft.AspNetCore.Http;
using System.IO;
using System.Text;

namespace FullCon2.Controllers
{
    public class KnowBasesController : BaseController
    {
        private readonly CoreDbContext _context;

        public KnowBasesController(CoreDbContext context)
        {
            _context = context;
        }

        // GET: KnowBases
        public async Task<IActionResult> Index()
        {
            var knowBase = await _context.knowBase.Include(a => a.knowbaseanexo).ToListAsync();

            return View(knowBase.OrderBy(b => b.descricao));
        }

        // GET: KnowBases/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var knowBase = await _context.knowBase
                .FirstOrDefaultAsync(m => m.Id == id);
            if (knowBase == null)
            {
                return NotFound();
            }

            return View(knowBase);
        }

        // GET: KnowBases/Create
        public async Task<IActionResult> Create(int? id)
        {
            if (id == null)
            {
                return View();
            }

            var knowBase = await _context.knowBase.Include(a => a.knowbaseanexo).FirstOrDefaultAsync(k => k.Id == id);

            if (knowBase == null)
            {
                return NotFound();
            }

            return View(knowBase);
        }

        // POST: KnowBases/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int? id, [Bind("erro,descricao,solucao,obs,Id")] KnowBase knowBase, IFormFile[] file, string[] idAnexo)
        {
            if (ModelState.IsValid)
            {
                List<KnowBaseAnexos> listAnexo = new List<KnowBaseAnexos>();

                if (knowBase.Id == id)
                {
                    for (int i = 0; i < file.Length; i++)
                    {
                        using (var ms = new MemoryStream())
                        {
                            KnowBaseAnexos anexo = new KnowBaseAnexos();
                            file[i].CopyTo(ms);
                            anexo.arquivo = ms.ToArray();
                            anexo.nome = file[i].FileName;
                            anexo.tipo = file[i].ContentType;

                            listAnexo.Add(anexo);
                        }

                    }

                    knowBase.knowbaseanexo = listAnexo;

                    _context.Update(knowBase);
                    await _context.SaveChangesAsync();

                }
                else
                {
                    for (int i = 0; i < file.Length; i++)
                    {
                        using (var ms = new MemoryStream())
                        {
                            file[i].CopyTo(ms);
                            listAnexo.Add(new KnowBaseAnexos()
                            {
                                arquivo = ms.ToArray(),
                                nome = file[i].Name,
                                tipo = file[i].ContentType
                            });
                        }
                    }

                    knowBase.knowbaseanexo = listAnexo;

                    _context.Add(knowBase);
                    await _context.SaveChangesAsync();

                }
            }
            //ViewData["IdCliente"] = new SelectList(_context.clientes, "Id", "Id", knowBase.IdCliente);
            //ViewData["IdKnowLocais"] = new SelectList(_context.knowLocais, "Id", "Id", knowBase.IdKnowLocais);
            //ViewData["IdKnowProduto"] = new SelectList(_context.knowProduto, "Id", "Id", knowBase.IdKnowProduto);
            //return View(knowBase);
            return RedirectToAction(nameof(Index));
        }


        // GET: KnowBases/Edit/5
        public IActionResult Edit(int? id)
        {
            return RedirectToAction("Create", "KnowBases", new { id });
        }

        // POST: KnowBases/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdCliente,IdKnowProduto,IdKnowLocais,erro,descricao,solucao,obs,versao,Id,DataInclusion,UserName")] KnowBase knowBase)
        {
            if (id != knowBase.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(knowBase);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!KnowBaseExists(knowBase.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            //ViewData["IdCliente"] = new SelectList(_context.clientes, "Id", "Id", knowBase.IdCliente);
            //ViewData["IdKnowLocais"] = new SelectList(_context.knowLocais, "Id", "Id", knowBase.IdKnowLocais);
            //ViewData["IdKnowProduto"] = new SelectList(_context.knowProduto, "Id", "Id", knowBase.IdKnowProduto);
            return View(knowBase);
        }



        public ActionResult ModalDelKnow(int id)
        {

            var model = _context.knowBase.FirstOrDefault(c => c.Id == id);

            return PartialView("modal_deleteknow", model);

        }

        public ActionResult ModalDelAnexo(int id)
        {

            var model = _context.knowBaseAnexo.FirstOrDefault(c => c.Id == id);

            return PartialView("modal_deleteknowanexo", model);

        }

        // POST: KnowBases/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var knowBase = await _context.knowBase.FindAsync(id);
            _context.knowBase.Remove(knowBase);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: KnowBases/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var knowBase = await _context.knowBase
                .FirstOrDefaultAsync(m => m.Id == id);
            if (knowBase == null)
            {
                return NotFound();
            }

            return View(knowBase);
        }

        private bool KnowBaseExists(int id)
        {
            return _context.knowBase.Any(e => e.Id == id);
        }



    }
}

FullCon2/Views/KnowBases/Create.cshtml
@model Domain.KnowBase
@addTagHelper *, Fluxmatix.AspNetCore.TagHelpers.QuillEditor

@{
    ViewData["Title"] = "Create";
}

<environment include="Staging, Production">
    <quill-editor-style-sheets></quill-editor-style-sheets>
</environment>

@*<script src="https://cdn.ckeditor.com/4.7.3/standard/ckeditor.js"></script>*@
@*<script src="~/js/ie10-viewport-bug-workaround.js"></script>*@

<br />
<h2 style="text-align:center">Knowledge Base</h2>
<hr />
<div class="panel-body pan">
    @*<div class="row">*@
    <div class="col-md-12 row">
        <form asp-action="Create" asp-controller="KnowBases" enctype="multipart/form-data">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            @if (Model != null && Model.Id > 0)
            {
                <input type="hidden" asp-for="Id" />
            }

            <div class="form-group row">
                <div class="col-md-1">
                    <label asp-for="descricao" class="control-label">Descrição</label>
                </div>
                <div class="col-md-11">
                    <input asp-for="descricao" class="form-control" />
                    <span asp-validation-for="descricao" class="text-danger"></span>
                </div>
            </div>


            <div class="form-group row">
                @*<div class="col-md-1">
                    <label asp-for="erro" class="control-label">Mensagem</label>
                </div>*@
                <div class="col-md-12">
                    @*<textarea class="editor" id="erro" asp-for="erro" style="height: 150px"></textarea>*@
                    <label asp-for="erro" class="control-label">Mensagem</label>
                    <quill-editor id="erro" asp-for="erro" style="background-color:white ; height: 150px">

                    </quill-editor>
                </div>

            </div>

            @*<br />
            <br />*@

            <div class="form-group row">
                @*<div class="col-md-1">
                    <label asp-for="solucao" class="control-label">Solução</label>
                </div>*@
                <div class="col-md-12">
                    <label asp-for="solucao" class="control-label">Solução</label>
                    <quill-editor id="solucao" asp-for="solucao" style="background-color:white ; height: 150px">

                    </quill-editor>
                </div>

            </div>
            @*<br />
            <br />*@

            <div class="form-group row">
                @*<div class="col-md-1">
                    <label asp-for="obs" class="control-label">Observação</label>
                </div>*@
                <div class="col-md-12">
                    <label asp-for="obs" class="control-label">Observação</label>
                    <quill-editor id="obs" asp-for="obs" style="background-color:white ; height: 150px">

                    </quill-editor>
                </div>
            </div>


            <div id="field" class="file">
                @if (Model == null)
                {
                    <div id="field0">
                        @*<partial name="_File" />*@
                    </div>
                }
                else
                {
                    @if (Model.knowbaseanexo != null && Model.knowbaseanexo.Any())
                    {
                        foreach (var item in Model.knowbaseanexo.OrderBy(n => n.nome))
                        {
                            <div class="form-group row">
                                <input type="hidden" name="idAnexo" asp-for="@item.Id" />
        
                                <div class="col-md-1">
                                    <button type="button" class="btn btn-success btn-sm mdi mdi-download " onclick="location.href='@Url.Action("DownloadAsync","KnowBaseAnexos", new { id = item.Id })'"></button>
                                </div>

                                <div class="col-md-10">
                                    @Html.DisplayFor(Model => item.nome)
                                </div>

                                <div class="col-md-1" style="text-align:right">
                                    <button type="button" class="btn btn-danger btn-sm mdi mdi-delete " onclick="abremodaldelknowanexo(@item.Id)"></button>

                                </div>
                            </div>

                        }
                    }
                    <div id="field0">
                        @*<partial name="_File" />*@
                    </div>
                }

            </div>

            <!-- Button -->
            <div class="form-group row">
                @*<div class="col-md-1">
                </div>*@
                <div class="col-md-11">
                    <input id="add-more" name="add-more" value="Add File" class="btn btn-default col-2" type="button" />
                </div>
            </div>

            <br />
            <br />

            <div class="row">
                <div class="col-md-1">
                    <input type="submit" value="Save" class="btn btn-success" />
                </div>
                <div class="col-md-10">
                </div>
                <div class="col-md-1">
                    @if (Model != null)
                    {
                        <input class="btn btn-danger" value="Remove" onclick="abremodaldelknow(@Model.Id)" type="button">
                    }

                </div>
            </div>







        </form>
    </div>
</div>




@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <quill-editor-script for-editors="obs,solucao,erro"></quill-editor-script>


    <script type="text/javascript">

        $(document).ready( function () {

            $('div').before(function () {
                $(this).removeAttr('data-placeholder');
            });

            $('#ql-editor').after(function () {
                $(this).style.backgroundColor = 'white';
            });

            var nFiledAdd = 0;
            var nextField = 0;
            $("#add-more").click(function (e) {

                e.preventDefault();
                
                var addto = "#field0";
                var _link = $('#field0').html();

                nextField = nextField + 1;

                if (nFiledAdd > 0 ) 
                    addto = "#field" + nFiledAdd;

                for (var i = nFiledAdd; i >= 0; i--) {
                    if ($(addto).length > 0) {
                        break;
                    } else {
                        addto = "#field" + i;
                    }
                }

                //prompt("Copy to clipboard: Ctrl+C, Enter", _link);

                var inputDelete = '<div id="field' + nextField + '" name="field' + nextField + '"  > ' + _link.replace(/value[^>]*(.*?)\s*\s*/g, '') + '<div class="form-group row" id="remove' + (nextField) + '" ><input type = "file" id = "action_file" name = "file" class="input-file col-md-11" ><div class="col-md-1" style="text-align:right"><button id="remove' + (nextField) + '" type="button" class="btn btn-danger btn-sm mdi mdi-delete remove-me"></button></div></div></div></div>'

                //alert(newIn + removeBtn);
                //prompt("Copy to clipboard: Ctrl+C, Enter", newIn + removeBtn);
                $(addto).after(inputDelete);


                $("#field" + nextField).attr('data-source', $(addto).attr('data-source'));
                $("#count").val(nextField);

                nFiledAdd = nFiledAdd + 1;

                $('.remove-me').click(function (e) {
                    e.preventDefault();
                    var fieldNum = this.id.charAt(this.id.length - 1);
                    var fieldID = "#field" + fieldNum;
                    var divID = "#remove" + fieldNum;
                    $(this).remove();
                    $(fieldID).remove();
                    $(divID).remove();
                });
            });

        });



        function abremodaldelknow(id) {
            var modal = $('#modalDel');
            var modalBody = modal.find('.modal-body');

            $.ajax({
                url: '@Url.Action("ModalDelKnow")',
                data: { id: id },
                success: function (data)
                {
                    modalBody.html(data);
                    modal.modal();
                }

            })
        };

        function abremodaldelknowanexo(id) {
            var modal = $('#modalDel');
            var modalBody = modal.find('.modal-body');

            $.ajax({
                url: '@Url.Action("ModalDelAnexo")',
                data: { id: id },
                success: function (data)
                {
                    modalBody.html(data);
                    modal.modal();
                }

            })
        };

    </script>
}


<div class="modal" id="modalDel">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">

                <h4 class="modal-title text-center">Confirme a exclusão</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default btn-xs" data-dismiss="modal">Cancelar</button>
            </div>
        </div>
    </div>
</div>

FullCon2/Views/KnowBases/Index.cshtml
@model IEnumerable<Domain.KnowBase>

@{
    ViewData["Title"] = "Index";
}

@*<h2>Index</h2>*@


@*<th>
        @Html.DisplayNameFor(model => model.erro)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.descricao)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.solucao)
    </th>*@
@*<th>
        @Html.DisplayNameFor(model => model.obs)
    </th>*@


<style value="text/css">
    #card1 {
        margin-top: 15px;
        border: 1px solid grey;
        box-shadow: 1px 0 2px 0;
    }

    #card-body1 {
        background-color: #e2e2e2;
    }

    #box-titulo {
        margin-top: 0px !important;
    }

    #button-edit {
        font-size: 15px;
        border-bottom-left-radius: 5px;
        border-bottom-right-radius: 5px;
    }

    #titulo {
        background-color: #1f262d;
        margin-left: 10px;
        font-size: 13px;
        color: #e2e2e2;
        font-weight: 900 !important;
        text-transform: uppercase;
        border-bottom-left-radius: 5px;
        border-bottom-right-radius: 5px;
        min-width: 50%;
        padding: 10px;
        float: left;
        margin-top: 0px !important;
        padding-right: 5%;
        padding-left: 3%;
    }

    #hr {
        width: 50%;
        height: 3px;
        background-color: #b6b6b6;
        color: #e2e2e2;
        float: inherit;
        text-align: center;
        vertical-align: middle;
        margin: auto;
        border: 0 none;
        border-radius: 5px;
        margin-top: 30px;
        margin-bottom: 30px
    }
</style>


@foreach (var item in Model)
{

    <div class="card" id="card1">
        <div class="card-body" style="padding-top:0px">
            <div class="row">
                <input type="hidden" name="knowid" asp-for="@item.Id" />
                <div class="col-md-10" id="box-titulo">
                    @if (!string.IsNullOrEmpty(item.descricao))
                    {
                        <h4 id="titulo"> @Html.DisplayFor(modelItem => item.descricao)</h4>
                    }
                </div>
                <div class="col-md-2" style="text-align:right">
                    <button type="button" class="btn btn-warning btn-sm mdi mdi-account-edit" id="button-edit" onclick="location.href='@Url.Action("Edit", new { id = item.Id })'"></button>
                </div>
                <div class="col-md-12">
                    <div class="card" style="background-color:white">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-6">
                                    <h5>Mensagem</h5>
                                    @Html.Raw(item.erro)
                                </div>
                                <div class="col-md-6">
                                    <h5>Solução</h5>
                                    @Html.Raw(item.solucao)
                                </div>
                            </div>
                        </div>
                        @if (!string.IsNullOrEmpty(item.obs))
                        {
                            <div class="col-md-12">
                                <div class="card">
                                    <div class="card-body" id="card-body1">
                                        <h5>Observação</h5>
                                        @Html.Raw(item.obs)
                                    </div>
                                </div>
                            </div>
                        }

                        @if (item.knowbaseanexo != null && item.knowbaseanexo.Any())
                        {
                            var line = 0;

                            <div class="form-group row">
                                 
                                @foreach (var anexo in item.knowbaseanexo.OrderBy(n => n.nome))
                                {
                                    line = line + 1;

                                    <input type="hidden" name="idAnexo" asp-for="@anexo.Id" />

                                    <div class="col-md-4">
                                        <button type="button" class="btn btn-success btn-sm mdi mdi-download " onclick="location.href='@Url.Action("DownloadAsync","KnowBaseAnexos", new { id = anexo.Id })'"></button>
                                        @Html.DisplayFor(Model => anexo.nome)
                                    </div>

                                    @if (line % 3 == 0 )
                                    {
                                        <div class="form-group row">&nbsp;
                                        </div>
                                    }

                                }
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
    <hr id="hr"/>
}

FullCon2/Views/KnowBases/_File.cshtml
<div class="form-group row" >
    <input type="file" id="action_file" name="file" class="input-file col-md-11">
</div>

FullCon2/Views/KnowBases/modal_deleteknow.cshtml
@model Domain.KnowBase

<div class="container-fluid">
    <form asp-action="Delete" asp-controller="KnowBases" method="post">
        <input type="hidden" name="id" asp-for="Id" />

        <h4>@Html.DisplayFor(Model => Model.descricao)</h4>
        <br />
        <br />
        <div class="form-actions no-color text-center">
            <button type="submit" class="btn btn-danger btn-sm">Deletar</button>
        </div>
    </form>
</div>

FullCon2/Views/KnowBases/modal_deleteknowanexo.cshtml
@model Domain.KnowBaseAnexos

<div class="container-fluid">
    <form asp-action="Delete" asp-controller="KnowBaseAnexos" method="post">
        <input type="hidden" name="id" asp-for="Id" />

        <h4>@Html.DisplayFor(Model => Model.nome)</h4>
        <br />
        <br />
        <div class="form-actions no-color text-center">
            <button type="submit" class="btn btn-danger btn-sm">Deletar</button>
        </div>
    </form>
</div>