FullCon2/Controllers/ClienteLinksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DBConnection;
using Domain;

namespace FullCon2.Controllers
{
    public class ClienteLinksController : BaseController
    {
        private readonly CoreDbContext _context;

        public ClienteLinksController(CoreDbContext context)
        {
            _context = context;
        }

        // GET: ClienteLinks
        public async Task<IActionResult> Index()
        {
            var coreDbContext = _context.clienteLinks.Include(c => c.cliente);
            return View(await coreDbContext.ToListAsync());
        }

        // GET: ClienteLinks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var clienteLinks = await _context.clienteLinks
                .Include(c => c.cliente)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (clienteLinks == null)
            {
                return NotFound();
            }

            return View(clienteLinks);
        }

        // GET: ClienteLinks/Create
        public IActionResult Create()
        {
            ViewData["IdCliente"] = new SelectList(_context.clientes, "Id", "Id");
            return View();
        }

        // POST: ClienteLinks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdCliente,link,usuario,senha,Id")] ClienteLinks clienteLinks)
        {
            if (ModelState.IsValid)
            {
                _context.Add(clienteLinks);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdCliente"] = new SelectList(_context.clientes, "Id", "Id", clienteLinks.IdCliente);
            return View(clienteLinks);
        }

        // GET: ClienteLinks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var clienteLinks = await _context.clienteLinks.FindAsync(id);
            if (clienteLinks == null)
            {
                return NotFound();
            }
            ViewData["IdCliente"] = new SelectList(_context.clientes, "Id", "Id", clienteLinks.IdCliente);
            return View(clienteLinks);
        }

        // POST: ClienteLinks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdCliente,link,usuario,senha,Id,DataInclusion,UserName")] ClienteLinks clienteLinks)
        {
            if (id != clienteLinks.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(clienteLinks);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClienteLinksExists(clienteLinks.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdCliente"] = new SelectList(_context.clientes, "Id", "Id", clienteLinks.IdCliente);
            return View(clienteLinks);
        }

        // GET: ClienteLinks/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var clienteLinks = await _context.clienteLinks
                .Include(c => c.cliente)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (clienteLinks == null)
            {
                return NotFound();
            }

            //var clienteLinks = await _context.clienteLinks.FindAsync(id);
            _context.clienteLinks.Remove(clienteLinks);
            await _context.SaveChangesAsync();
            //return RedirectToAction(nameof(Index));
            return RedirectToAction("Create", "Clientes", new { id = clienteLinks.cliente.Id });

            //return View(clienteLinks);
        }

        // POST: ClienteLinks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var clienteLinks = await _context.clienteLinks.FindAsync(id);
            _context.clienteLinks.Remove(clienteLinks);
            await _context.SaveChangesAsync();
            //return RedirectToAction(nameof(Index));
            return RedirectToAction("Create", "Clientes", new { id = clienteLinks.IdCliente });
        }

        private bool ClienteLinksExists(int id)
        {
            return _context.clienteLinks.Any(e => e.Id == id);
        }
    }
}

FullCon2/Controllers/ClientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DBConnection;
using Domain;
using System.Net;
using System.Threading;
using System.IO;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;

namespace FullCon2.Controllers
{
    public class ClientesController : BaseController
    {
        private readonly CoreDbContext _context;

        public ClientesController(CoreDbContext context)
        {
            _context = context;
        }

        // GET: Clientes
        public async Task<IActionResult> Index()
        {
            var cli = await _context.clientes.Include(c => c.clientelinks).Include(c => c.clienteconexao).Include(c => c.clienteanexos).ToListAsync();

            return View(cli.OrderBy(c => c.nome));
        }

        // GET: Clientes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var clientes = await _context.clientes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (clientes == null)
            {
                return NotFound();
            }

            return View(clientes);
        }

        // GET: Clientes/Create
        public async Task<IActionResult> Create(int? id)
        {
            if (id == null)
            {
                return View();
            }

            Clientes clientes = await _context.clientes.Include(c => c.clientelinks).Include(c => c.clienteconexao).Include(c => c.clienteanexos).FirstOrDefaultAsync(c => c.Id == id);

            if (clientes == null)
            {
                return NotFound();
            }

            return View(clientes);

        }


        // POST: Clientes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int? id, [Bind("nome,obs,Id")] Clientes clientes
                                               , string[] link , string[] user, string[] pass, string[] nomelink, int?[] linkid
                                               , string[] conexao_pass, string[] conexao_user, string[] conexao_ip, string[] conexao_desc, string[] obsConexao,  int?[] conexao_id 
                                               , IFormFile[] file, string[] idAnexo)
        {
            if (ModelState.IsValid)
            {
                List<ClienteLinks> cliLink = new List<ClienteLinks>();
                List<ClienteAnexos> cliAnexo = new List<ClienteAnexos>();
                List<ClienteConexoes> cliConexao = new List<ClienteConexoes>();

                if (clientes.Id == id)
                {
                    try
                    {
                        for (int i = 0; i < linkid.Length; i++)
                        {
                            try
                            {
                                if (linkid[i].ToString() != null && !string.IsNullOrEmpty(linkid[i].ToString()))
                                {
                                    try
                                    {
                                        var idlink = string.IsNullOrEmpty(linkid[i].ToString());

                                        if (!string.IsNullOrEmpty(linkid[i].ToString()))
                                        {
                                            ClienteLinks clienteLinks = _context.clienteLinks.Find(linkid[i]);
                                            clienteLinks.link = link[i];
                                            clienteLinks.senha = pass[i];
                                            clienteLinks.usuario = user[i];
                                            clienteLinks.nome = nomelink[i];

                                            cliLink.Add(clienteLinks);
                                        }
                                    }
                                    catch
                                    {
                                        cliLink.Add(new ClienteLinks()
                                        {
                                            link = link[i],
                                            senha = pass[i],
                                            usuario = user[i],
                                            nome = nomelink[i]
                                        });
                                    }
                                }

                                clientes.clientelinks = cliLink;
                            }
                            catch
                            { }
                        }


                        for (int i = 0; i < conexao_id.Length; i++)
                        {
                            try
                            {
                                if ( conexao_id[i].ToString() != null && !string.IsNullOrEmpty(conexao_id[i].ToString()))
                                {
                                    try
                                    {
                                        var id_conexao = string.IsNullOrEmpty(conexao_id[i].ToString());

                                        if (!string.IsNullOrEmpty(conexao_id[i].ToString()))
                                        {
                                            ClienteConexoes clicon = _context.clienteConexoes.Find(conexao_id[i]);

                                            clicon.descricao  = conexao_desc[i];
                                            clicon.senha = conexao_pass[i];
                                            clicon.usuario = conexao_user[i];
                                            clicon.ip = conexao_ip[i];
                                            clicon.obsConexao = obsConexao[i];

                                            cliConexao.Add(clicon);
                                        }
                                    }
                                    catch
                                    {
                                        cliConexao.Add(new ClienteConexoes()
                                        {
                                            descricao = conexao_desc[i],
                                            ip = conexao_ip[i],
                                            senha = conexao_pass[i],
                                            usuario = conexao_user[i],
                                            obsConexao = obsConexao[i]
                                        });
                                    }
                                }

                                clientes.clienteconexao = cliConexao;
                            }
                            catch
                            { }
                        }

                        try
                        {
                            for (int a = 0; a < file.Length; a++)
                            {
                                try
                                {
                                    using (var ms = new MemoryStream())
                                    {
                                        ClienteAnexos anexo = new ClienteAnexos();
                                        file[a].CopyTo(ms);
                                        anexo.arquivo = ms.ToArray();
                                        anexo.nome = file[a].FileName;
                                        anexo.tipo = file[a].ContentType;

                                        cliAnexo.Add(anexo);
                                    }

                                }
                                catch
                                { }

                            }
                            clientes.clienteanexos = cliAnexo;
                        }
                        catch
                        { }

                        _context.Update(clientes);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!ClientesExists(clientes.Id))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }



                    //return RedirectToAction(nameof(Edit));
                    //return RedirectToAction(nameof(Index));
                }
                else
                {
                    //_context.Add(clientes);
                    //List<ClienteLinks> cl = new List<ClienteLinks>();

                    for (int i = 0; i < link.Length; i++)
                    {
                        cliLink.Add(new ClienteLinks()
                        {
                            link = link[i],
                            senha = pass[i],
                            usuario = user[i],
                            nome = nomelink[i]
                        });
                    }

                    for (int i = 0; i < conexao_desc.Length; i++)
                    {
                        cliConexao.Add(new ClienteConexoes()
                        {
                            descricao = conexao_desc[i],
                            ip = conexao_ip[i],
                            senha = conexao_pass[i],
                            usuario = conexao_user[i],
                            obsConexao = obsConexao[i]
                        });
                    }

                    for (int i = 0; i < file.Length; i++)
                    {
                        using (var ms = new MemoryStream())

FullCon2/Views/Clientes/Index.cshtml
@model IEnumerable<Domain.Clientes>

@{
    ViewData["Title"] = "Index";
}
<br />

@foreach (var item in Model)
{
    <div class="card">
        <div class="card-body">
            <div class="row">
                <input type="hidden" name="cliid" asp-for="@item.Id" />
                <div class="col-md-10">
                    <h4>@Html.DisplayFor(modelItem => item.nome)</h4>
                </div>
                <div class="col-md-2" style="text-align:right">

                    @if (!string.IsNullOrEmpty(item.obs))
                    {
                        <button type="button" class="btn btn-default btn-sm mdi mdi-information-variant" onclick="abremodalobs(@item.Id)"></button>
                    }


                    @if (item.clienteanexos.Any())
                    {
                        <button type="button" class="btn btn-success btn-sm mdi mdi-download" onclick="abremodalanexocli(@item.Id)"></button>
                    }

                    @if (item.clienteconexao.Any())
                    {
                        <button type="button" class="btn btn-cyan btn-sm mdi mdi-desktop-mac" onclick="location.href='@Url.Action("Index","ClienteConexoes", new { id = item.Id })'"></button>
                    }


                    <button type="button" class="btn btn-warning btn-sm mdi mdi-account-edit" onclick="location.href='@Url.Action("Edit", new { id = item.Id })'"></button>

                </div>

            </div>


            @if (item.clientelinks != null && item.clientelinks.Any())
            {
                foreach (var link in item.clientelinks.OrderBy(o => o.nome))
                {

                    <div id="@link.Id" class="col-md-12 row">

                        <div class="col-md-2" style="font-weight:bold;text-align:right">
                            @Html.DisplayFor(modelItem => link.nome)
                        </div>
                        @if (!string.IsNullOrEmpty(@link.link))
                        {
                            <div class="td-cliente col-md-6 row">
                                <div class="mdi">
                                    <i class="icone fa fa-spinner fa-spin" style="font-size:13px"></i>
                                    <br />
                                </div>
                                <a href="http://@link.link" target="_blank" class="link text-cyan "> @Html.DisplayFor(modelItem => link.link) </a>
                            </div>
                        }
                        <div class="col-md-2" style="text-align:right">
                            @Html.DisplayFor(modelItem => link.usuario)
                        </div>
                        <div class="col-md-2">
                            @Html.DisplayFor(modelItem => link.senha)
                        </div>
                    </div>

                }
            }

            @*<hr />*@
        </div>
    </div>
}


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script type="text/javascript">

        var jqXHR;
        var ajaxRequestsArray = [];


        $(".btn").click(function (e) {
            e.preventDefault();
            for (var i = 0; i < ajaxRequestsArray.length; i++) {
                var curRequest = ajaxRequestsArray[i];
                curRequest.abort();
            }
        });

        function abremodalanexocli(id) {
            var modal = $('#modalAnexo');
            var modalBody = modal.find('.modal-body');

            $.ajax({
                url: '@Url.Action("ModalAnexoCliente")',
                data: { id: id },
                success: function (data)
                {
                    modalBody.html(data);
                    modal.modal();
                }

            })
        };


        function abremodalobs(id) {
            var modal = $('#modalObs');
            var modalBody = modal.find('.modal-body');

            $.ajax({
                url: '@Url.Action("ModalObs")',
                data: { id: id },
                success: function (data)
                {
                    modalBody.html(data);
                    modal.modal();
                }

            })
        };

        function testeUrl() {
            $('.td-cliente').each(function () {
                var classeCarregando = 'icone fa fa-spinner fa-spin';

                var item = $(this);

                var link = item.find('a');
                var icone = item.find('.icone');

                icone.removeClass();

                icone.addClass(classeCarregando);

                var classeLinkAtivo = 'mdi icone mdi-check-circle-outline text-success';
                var classeLinkInativo = 'mdi icone mdi-alert-circle-outline text-danger';

                //jqXHR
                ajaxRequest   = $.ajax({
                    url: '@Url.Action("TesteUrl")',
                    data: { endereco: link.attr('href') },
                    async : true,
                    success: function (data) {
                        icone.removeClass(classeCarregando);
                        if (data == true) {
                            icone.addClass(classeLinkAtivo);
                        }
                        else {
                            icone.addClass(classeLinkInativo);
                        }
                    },
                    error: function () {
                        icone.removeClass(classeCarregando);
                        icone.addClass(classeLinkInativo);
                    }

                });

                ajaxRequestsArray.push(ajaxRequest);

            });
        };

        setInterval("testeUrl()", 60000);

        $(function () {
            // Faz a primeira atualização
            testeUrl();
        });

    </script>
}


<!-- Modal obs -->
<div class="modal" id="modalObs">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title text-center">Observações</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default btn-xs" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>


<!-- Modal Anexo -->
<div class="modal" id="modalAnexo">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title text-center">Arquivos</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default btn-xs" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>

FullCon2/Views/Clientes/_Link.cshtml
<div class="form-group row">
    <label class="col-sm-2 text-right control-label col-form-label">Nome</label>
    <div class="col-md-8">
        <input id="nome_id" name="nomelink" type="text" placeholder="" class="form-control input-md">
    </div>
</div>
<div class="form-group row">
    <label class="col-sm-2 text-right control-label col-form-label">Link</label>
    <div class="col-md-8">
        <input id="link_id" name="link" type="text" placeholder="" class="form-control input-md">
    </div>
</div>
<div class="form-group row">
    <label class="col-sm-2 text-right control-label col-form-label">Usuario</label>
    <div class="col-md-5">
        <input id="user_name" name="user" type="text" placeholder="" class="form-control input-md">
    </div>
</div>
<div class="form-group row">
    <label class="col-sm-2 text-right control-label col-form-label">Senha</label>
    <div class="col-md-5">
        <input id="pass_name" name="pass" type="text" placeholder="" class="form-control input-md">
    </div>
</div>
<hr />

FullCon2/Views/Clientes/modal_anexo.cshtml
@model Domain.Clientes

@if (Model.clienteanexos != null && Model.clienteanexos.Any())
{
    var line = 0;

    <div class="form-group row">

        @foreach (var anexo in Model.clienteanexos.OrderBy(n => n.nome))
        {
            line = line + 1;

            <input type="hidden" name="idAnexo" asp-for="@anexo.Id" />

            <div class="col-md-10">
                <button type="button" class="btn btn-success btn-sm mdi mdi-download " onclick="location.href='@Url.Action("DownloadAsync","ClienteAnexos", new { id = anexo.Id })'"></button>
                @Html.DisplayFor(Model => anexo.nome)
            </div>

            @if (line % 1 == 0)
            {
                <div class="form-group row">
                    &nbsp;
                </div>
            }

        }
    </div>
}

FullCon2/Views/Clientes/modal_delete.cshtml
@model Domain.ClienteLinks

<div class="container-fluid">
    <form asp-action="Delete" asp-controller="ClienteLinks" method="post">
        <input type="hidden" name="id" asp-for="Id" />

        <dl class="dl-horizontal">

            <dd>
                @Html.DisplayFor(model => model.nome)
            </dd>

            <dd>
                @Html.DisplayFor(model => model.link)
            </dd>
        </dl>

        <div class="form-actions no-color text-center">
            <button type="submit" class="btn btn-danger btn-sm">Deletar</button>
        </div>

    </form>
</div>

FullCon2/Views/Clientes/modal_deleteclianexo.cshtml
@model Domain.ClienteAnexos

<div class="container-fluid">
    <form asp-action="Delete" asp-controller="ClienteAnexos" method="post">
        <input type="hidden" name="id" asp-for="Id" />

        <h4>@Html.DisplayFor(Model => Model.nome)</h4>
        <br />
        <br />
        <div class="form-actions no-color text-center">
            <button type="submit" class="btn btn-danger btn-sm">Deletar</button>
        </div>
    </form>
</div>

FullCon2/Views/Clientes/modal_deletecliente.cshtml
@model Domain.Clientes

<div class="container-fluid">
    <form asp-action="Delete" asp-controller="Clientes" method="post">
        <input type="hidden" name="id" asp-for="Id" />

        <dl class="dl-horizontal">
            <dt>
                Nome
            </dt>

            <dd>
                @Html.DisplayFor(model => model.nome)
            </dd>

        </dl>

        <div class="form-actions no-color text-center">
            <button type="submit" class="btn btn-danger btn-sm  ">Deletar</button>
        </div>
    </form>

</div>

FullCon2/Views/Clientes/modal_obs.cshtml
@model Domain.Clientes

<div>
    @Html.Raw(Model.obs)
</div>